

data = {
    "animal": ['abelha', 'aranha', 'baleia', 'cachorro', 'cavalo', 'crocodilo', 'dromedário', 'elefante', 'foca', 'gato', 'girafa', 'hamster', 'hiena', 'hipopótamo', 'iguana', 'jacaré', 'leopardo', 'leão', 'macaco', 'nutria', 'onça', 'panda', 'pássaro', 'quati', 'raposa', 'rato', 'sapo', 'suricate', 'tigre', 'touro', 'tucano', 'unicórnio', 'urso', 'vaca', 'zebra', 'águia'],
    "país": ["Brasil", "Argentina", "Chile", "Uruguai", "Paraguai", "Bolívia", "Peru", "Equador", "Colômbia", "Venezuela", "Suriname", "Guiana", "Guyana", "França", "Inglaterra"],
    "fruta": ["maçã", "banana", "laranja", "abacaxi", "mamão", "goiaba", "melancia", "morango", "pera", "uva", "manga", "kiwi", "abacate", "caju", "tangerina"],
    "vegetal": ["cenoura", "beterraba", "abóbora", "repolho", "brócolis", "couve", "espinafre", "alface", "cebola", "pimentão", "tomate", "batata", "abacate", "ervilha", "feijão"],
    "cor": ["vermelho", "laranja", "amarelo", "verde", "azul", "anil", "roxo", "rosa", "marrom", "preto", "branco", "cinza", "dourado", "prateado", "bronze"],
    "cantor": ["Roberto Carlos", "Chico Buarque", "Milton Nascimento", "Caetano Veloso", "Gal Costa", "Gilberto Gil", "Maria Bethânia", "Jorge Ben Jor", "Fagner", "Elis Regina", "Cazuza", "Renato Russo", "Tim Maia", "Djavan", "Zeca Pagodinho", "Seu Jorge", "Anitta", "Luan Santana", "Ivete Sangalo", "Wesley Safadão"],
    "esporte": ["futebol", "basquete", "vôlei", "tênis", "natação", "atletismo", "boxe", "skate", "surfe", "ciclismo", "futebol americano", "beisebol", "hóquei", "rugby", "cricket"],
    "profissão": ["médico", "advogado", "engenheiro", "arquiteto", "professor", "jornalista", "dentista", "físico", "astronomo", "geólogo", "biólogo", "químico", "farmacêutico", "veterinário", "psicólogo"],
    "marca": ["Nike", "Adidas", "Puma", "Reebok", "Under Armour", "New Balance", "Asics", "Converse", "Vans", "Timberland", "Levi's", "Calvin Klein", "Tommy Hilfiger", "Ralph Lauren", "Gucci"],
    "filme":  ['12 Anos de Escravidão', 'A Bela e a Fera', 'A Origem', 'Ace Ventura', 'Avatar', 'Batman O Cavaleiro das Trevas', 'Capitã Marvel', 'Cidade de Deus', 'Cão de Briga', 'Donnie Darko', 'Ex Machina', 'Frozen', 'Gravidade', 'Guardiões da Galáxia', 'Homem Aranha Longe de Casa', 'Interestelar', 'Jurassic Park', 'Laranja Mecânica', 'Mad Max', 'Mundo Jurássico', 'O Auto da Compadecida', 'O Boxtrolls', 'O Clube de La Pele', 'O Grande Hotel Budapeste', 'O Grande Lebowski', 'O Lado Bom da Vida', 'O Laço Branco', 'O Lutador', 'O Poderoso Chefão', 'O Prestígio', 'O Regresso', 'O Rei Leão', 'Os Incríveis', 'Os Vingadores', 'Pantera Negra', 'Pulp Fiction', 'Rocky Balboa', 'Snakes on a Plane', 'Star Wars O Despertar da Força', 'Titanic', 'Toy Story', 'Tropa de Elite', 'Velozes e Furiosos', 'Vingadores Ultimato']}